id = "quantum-void"
name = "Quantum Void Themes"
version = "0.1.0"
schema_version = 1
authors = ["Luncert <2725115515@qq.com>"]
description = "Quantum Void Themes"
repository = "https://github.com/Luncert/QuantumVoid"
